/* =====================================================
   NutriTrack — Comprehensive Food Database
   500+ foods with full nutritional data per serving
   ===================================================== */

export const FOOD_DATABASE = [
    // ==================== PROTEIN / MEATS ====================
    { id: 1, name: "Chicken Breast (Grilled)", brand: "Generic", category: "protein", emoji: "🍗", serving: "100g", calories: 165, protein: 31, carbs: 0, fat: 3.6, fiber: 0, sugar: 0, sodium: 74, cholesterol: 85 },
    { id: 2, name: "Chicken Thigh (Skin-on)", brand: "Generic", category: "protein", emoji: "🍗", serving: "100g", calories: 209, protein: 26, carbs: 0, fat: 11, fiber: 0, sugar: 0, sodium: 84, cholesterol: 130 },
    { id: 3, name: "Chicken Wings", brand: "Generic", category: "protein", emoji: "🍗", serving: "4 wings (100g)", calories: 203, protein: 30, carbs: 0, fat: 8, fiber: 0, sugar: 0, sodium: 77, cholesterol: 89 },
    { id: 4, name: "Turkey Breast (Roasted)", brand: "Generic", category: "protein", emoji: "🦃", serving: "100g", calories: 135, protein: 30, carbs: 0, fat: 1, fiber: 0, sugar: 0, sodium: 46, cholesterol: 83 },
    { id: 5, name: "Salmon (Atlantic, cooked)", brand: "Generic", category: "protein", emoji: "🐟", serving: "100g", calories: 208, protein: 20, carbs: 0, fat: 13, fiber: 0, sugar: 0, sodium: 59, cholesterol: 55 },
    { id: 6, name: "Tuna (canned in water)", brand: "Generic", category: "protein", emoji: "🐟", serving: "1 can (142g)", calories: 179, protein: 39, carbs: 0, fat: 1.4, fiber: 0, sugar: 0, sodium: 468, cholesterol: 60 },
    { id: 7, name: "Shrimp (cooked)", brand: "Generic", category: "protein", emoji: "🦐", serving: "100g", calories: 99, protein: 24, carbs: 0.2, fat: 0.3, fiber: 0, sugar: 0, sodium: 111, cholesterol: 189 },
    { id: 8, name: "Beef Sirloin (lean)", brand: "Generic", category: "protein", emoji: "🥩", serving: "100g", calories: 183, protein: 27, carbs: 0, fat: 8, fiber: 0, sugar: 0, sodium: 56, cholesterol: 82 },
    { id: 9, name: "Ground Beef (80/20)", brand: "Generic", category: "protein", emoji: "🥩", serving: "100g", calories: 254, protein: 17, carbs: 0, fat: 20, fiber: 0, sugar: 0, sodium: 66, cholesterol: 80 },
    { id: 10, name: "Ground Beef (90/10)", brand: "Generic", category: "protein", emoji: "🥩", serving: "100g", calories: 176, protein: 20, carbs: 0, fat: 10, fiber: 0, sugar: 0, sodium: 66, cholesterol: 70 },
    { id: 11, name: "Pork Chop (boneless)", brand: "Generic", category: "protein", emoji: "🥩", serving: "100g", calories: 231, protein: 25, carbs: 0, fat: 14, fiber: 0, sugar: 0, sodium: 62, cholesterol: 72 },
    { id: 12, name: "Bacon (cooked)", brand: "Generic", category: "protein", emoji: "🥓", serving: "3 slices (35g)", calories: 161, protein: 12, carbs: 0.4, fat: 12, fiber: 0, sugar: 0, sodium: 581, cholesterol: 40 },
    { id: 13, name: "Ham (sliced)", brand: "Generic", category: "protein", emoji: "🍖", serving: "100g", calories: 145, protein: 21, carbs: 1.5, fat: 6, fiber: 0, sugar: 0, sodium: 1203, cholesterol: 57 },
    { id: 14, name: "Lamb Chop", brand: "Generic", category: "protein", emoji: "🍖", serving: "100g", calories: 258, protein: 26, carbs: 0, fat: 17, fiber: 0, sugar: 0, sodium: 72, cholesterol: 97 },
    { id: 15, name: "Tilapia (baked)", brand: "Generic", category: "protein", emoji: "🐟", serving: "100g", calories: 128, protein: 26, carbs: 0, fat: 2.7, fiber: 0, sugar: 0, sodium: 56, cholesterol: 57 },
    { id: 16, name: "Cod (baked)", brand: "Generic", category: "protein", emoji: "🐟", serving: "100g", calories: 105, protein: 23, carbs: 0, fat: 0.9, fiber: 0, sugar: 0, sodium: 78, cholesterol: 55 },
    { id: 17, name: "Sardines (canned)", brand: "Generic", category: "protein", emoji: "🐟", serving: "1 can (92g)", calories: 191, protein: 23, carbs: 0, fat: 11, fiber: 0, sugar: 0, sodium: 307, cholesterol: 131 },
    { id: 18, name: "Egg (whole, large)", brand: "Generic", category: "protein", emoji: "🥚", serving: "1 egg (50g)", calories: 72, protein: 6.3, carbs: 0.4, fat: 5, fiber: 0, sugar: 0.2, sodium: 71, cholesterol: 186 },
    { id: 19, name: "Egg Whites", brand: "Generic", category: "protein", emoji: "🥚", serving: "3 whites (99g)", calories: 51, protein: 11, carbs: 0.7, fat: 0.2, fiber: 0, sugar: 0.6, sodium: 164, cholesterol: 0 },
    { id: 20, name: "Tofu (firm)", brand: "Generic", category: "protein", emoji: "🧈", serving: "100g", calories: 76, protein: 8, carbs: 1.9, fat: 4.8, fiber: 0.3, sugar: 0.6, sodium: 7, cholesterol: 0 },
    { id: 21, name: "Tempeh", brand: "Generic", category: "protein", emoji: "🧈", serving: "100g", calories: 192, protein: 20, carbs: 8, fat: 11, fiber: 5, sugar: 0, sodium: 9, cholesterol: 0 },
    { id: 22, name: "Protein Powder (Whey)", brand: "Generic", category: "protein", emoji: "🥤", serving: "1 scoop (30g)", calories: 120, protein: 24, carbs: 3, fat: 1, fiber: 0, sugar: 1, sodium: 130, cholesterol: 20 },
    { id: 23, name: "Protein Powder (Plant)", brand: "Generic", category: "protein", emoji: "🥤", serving: "1 scoop (33g)", calories: 130, protein: 21, carbs: 6, fat: 2.5, fiber: 2, sugar: 1, sodium: 300, cholesterol: 0 },
    { id: 24, name: "Cottage Cheese (2%)", brand: "Generic", category: "protein", emoji: "🧀", serving: "1 cup (226g)", calories: 183, protein: 24, carbs: 10, fat: 5, fiber: 0, sugar: 9, sodium: 746, cholesterol: 24 },
    { id: 25, name: "Beef Jerky", brand: "Generic", category: "protein", emoji: "🥩", serving: "1 oz (28g)", calories: 116, protein: 9, carbs: 3, fat: 7, fiber: 0.4, sugar: 3, sodium: 590, cholesterol: 14 },

    // ==================== GRAINS & CARBS ====================
    { id: 50, name: "White Rice (cooked)", brand: "Generic", category: "grains", emoji: "🍚", serving: "1 cup (158g)", calories: 206, protein: 4.3, carbs: 45, fat: 0.4, fiber: 0.6, sugar: 0, sodium: 1, cholesterol: 0 },
    { id: 51, name: "Brown Rice (cooked)", brand: "Generic", category: "grains", emoji: "🍚", serving: "1 cup (195g)", calories: 216, protein: 5, carbs: 45, fat: 1.8, fiber: 3.5, sugar: 0.7, sodium: 10, cholesterol: 0 },
    { id: 52, name: "Quinoa (cooked)", brand: "Generic", category: "grains", emoji: "🌾", serving: "1 cup (185g)", calories: 222, protein: 8.1, carbs: 39, fat: 3.6, fiber: 5.2, sugar: 1.6, sodium: 13, cholesterol: 0 },
    { id: 53, name: "Oatmeal (cooked)", brand: "Generic", category: "grains", emoji: "🥣", serving: "1 cup (234g)", calories: 154, protein: 5.4, carbs: 27, fat: 2.6, fiber: 4, sugar: 0.6, sodium: 115, cholesterol: 0 },
    { id: 54, name: "Whole Wheat Bread", brand: "Generic", category: "grains", emoji: "🍞", serving: "1 slice (28g)", calories: 69, protein: 3.6, carbs: 12, fat: 1.1, fiber: 1.9, sugar: 1.4, sodium: 132, cholesterol: 0 },
    { id: 55, name: "White Bread", brand: "Generic", category: "grains", emoji: "🍞", serving: "1 slice (25g)", calories: 67, protein: 2, carbs: 13, fat: 0.8, fiber: 0.6, sugar: 1.4, sodium: 130, cholesterol: 0 },
    { id: 56, name: "Pasta (cooked)", brand: "Generic", category: "grains", emoji: "🍝", serving: "1 cup (140g)", calories: 220, protein: 8.1, carbs: 43, fat: 1.3, fiber: 2.5, sugar: 0.8, sodium: 1, cholesterol: 0 },
    { id: 57, name: "Whole Wheat Pasta (cooked)", brand: "Generic", category: "grains", emoji: "🍝", serving: "1 cup (140g)", calories: 174, protein: 7.5, carbs: 37, fat: 0.8, fiber: 6.3, sugar: 0.8, sodium: 4, cholesterol: 0 },
    { id: 58, name: "Tortilla (Flour, 10\")", brand: "Generic", category: "grains", emoji: "🌮", serving: "1 tortilla (72g)", calories: 218, protein: 5.7, carbs: 36, fat: 5.4, fiber: 2.1, sugar: 1.8, sodium: 405, cholesterol: 0 },
    { id: 59, name: "Corn Tortilla", brand: "Generic", category: "grains", emoji: "🌮", serving: "1 tortilla (26g)", calories: 52, protein: 1.4, carbs: 11, fat: 0.7, fiber: 1.5, sugar: 0.2, sodium: 11, cholesterol: 0 },
    { id: 60, name: "Bagel (plain)", brand: "Generic", category: "grains", emoji: "🥯", serving: "1 bagel (105g)", calories: 270, protein: 11, carbs: 53, fat: 1.6, fiber: 2.3, sugar: 6, sodium: 443, cholesterol: 0 },
    { id: 61, name: "Granola", brand: "Generic", category: "grains", emoji: "🥣", serving: "1/2 cup (55g)", calories: 264, protein: 6.5, carbs: 35, fat: 12, fiber: 3.5, sugar: 14, sodium: 15, cholesterol: 0 },
    { id: 62, name: "Cornflakes", brand: "Kellogg's", category: "grains", emoji: "🥣", serving: "1 cup (28g)", calories: 101, protein: 1.9, carbs: 24, fat: 0.2, fiber: 0.7, sugar: 2.4, sodium: 200, cholesterol: 0 },
    { id: 63, name: "Sweet Potato (baked)", brand: "Generic", category: "grains", emoji: "🍠", serving: "1 medium (114g)", calories: 103, protein: 2.3, carbs: 24, fat: 0.1, fiber: 3.8, sugar: 7.4, sodium: 41, cholesterol: 0 },
    { id: 64, name: "Potato (baked)", brand: "Generic", category: "grains", emoji: "🥔", serving: "1 medium (173g)", calories: 161, protein: 4.3, carbs: 37, fat: 0.2, fiber: 3.8, sugar: 1.9, sodium: 17, cholesterol: 0 },
    { id: 65, name: "French Fries", brand: "Generic", category: "grains", emoji: "🍟", serving: "medium (117g)", calories: 365, protein: 4, carbs: 44, fat: 19, fiber: 4, sugar: 0.3, sodium: 246, cholesterol: 0 },
    { id: 66, name: "Couscous (cooked)", brand: "Generic", category: "grains", emoji: "🌾", serving: "1 cup (157g)", calories: 176, protein: 6, carbs: 36, fat: 0.3, fiber: 2.2, sugar: 0.1, sodium: 8, cholesterol: 0 },
    { id: 67, name: "Naan Bread", brand: "Generic", category: "grains", emoji: "🍞", serving: "1 piece (90g)", calories: 262, protein: 9, carbs: 45, fat: 5.1, fiber: 2, sugar: 3, sodium: 418, cholesterol: 0 },
    { id: 68, name: "Pita Bread (whole wheat)", brand: "Generic", category: "grains", emoji: "🍞", serving: "1 pita (64g)", calories: 170, protein: 6.3, carbs: 35, fat: 1.7, fiber: 4.7, sugar: 0.7, sodium: 340, cholesterol: 0 },
    { id: 69, name: "Rice Cakes", brand: "Generic", category: "grains", emoji: "🍘", serving: "2 cakes (18g)", calories: 70, protein: 1.4, carbs: 15, fat: 0.5, fiber: 0.4, sugar: 0.1, sodium: 29, cholesterol: 0 },
    { id: 70, name: "Popcorn (air-popped)", brand: "Generic", category: "grains", emoji: "🍿", serving: "3 cups (24g)", calories: 93, protein: 3, carbs: 19, fat: 1.1, fiber: 3.5, sugar: 0.2, sodium: 2, cholesterol: 0 },

    // ==================== FRUITS ====================
    { id: 100, name: "Banana", brand: "Generic", category: "fruits", emoji: "🍌", serving: "1 medium (118g)", calories: 105, protein: 1.3, carbs: 27, fat: 0.4, fiber: 3.1, sugar: 14, sodium: 1, cholesterol: 0 },
    { id: 101, name: "Apple", brand: "Generic", category: "fruits", emoji: "🍎", serving: "1 medium (182g)", calories: 95, protein: 0.5, carbs: 25, fat: 0.3, fiber: 4.4, sugar: 19, sodium: 2, cholesterol: 0 },
    { id: 102, name: "Orange", brand: "Generic", category: "fruits", emoji: "🍊", serving: "1 medium (131g)", calories: 62, protein: 1.2, carbs: 15, fat: 0.2, fiber: 3.1, sugar: 12, sodium: 0, cholesterol: 0 },
    { id: 103, name: "Strawberries", brand: "Generic", category: "fruits", emoji: "🍓", serving: "1 cup (152g)", calories: 49, protein: 1, carbs: 12, fat: 0.5, fiber: 3, sugar: 7.4, sodium: 2, cholesterol: 0 },
    { id: 104, name: "Blueberries", brand: "Generic", category: "fruits", emoji: "🫐", serving: "1 cup (148g)", calories: 84, protein: 1.1, carbs: 21, fat: 0.5, fiber: 3.6, sugar: 15, sodium: 1, cholesterol: 0 },
    { id: 105, name: "Grapes", brand: "Generic", category: "fruits", emoji: "🍇", serving: "1 cup (151g)", calories: 104, protein: 1.1, carbs: 27, fat: 0.2, fiber: 1.4, sugar: 23, sodium: 3, cholesterol: 0 },
    { id: 106, name: "Watermelon", brand: "Generic", category: "fruits", emoji: "🍉", serving: "1 cup diced (152g)", calories: 46, protein: 0.9, carbs: 12, fat: 0.2, fiber: 0.6, sugar: 9.4, sodium: 2, cholesterol: 0 },
    { id: 107, name: "Mango", brand: "Generic", category: "fruits", emoji: "🥭", serving: "1 cup sliced (165g)", calories: 99, protein: 1.4, carbs: 25, fat: 0.6, fiber: 2.6, sugar: 23, sodium: 2, cholesterol: 0 },
    { id: 108, name: "Pineapple", brand: "Generic", category: "fruits", emoji: "🍍", serving: "1 cup chunks (165g)", calories: 82, protein: 0.9, carbs: 22, fat: 0.2, fiber: 2.3, sugar: 16, sodium: 2, cholesterol: 0 },
    { id: 109, name: "Avocado", brand: "Generic", category: "fruits", emoji: "🥑", serving: "1/2 avocado (68g)", calories: 114, protein: 1.3, carbs: 6, fat: 10, fiber: 4.6, sugar: 0.2, sodium: 5, cholesterol: 0 },
    { id: 110, name: "Peach", brand: "Generic", category: "fruits", emoji: "🍑", serving: "1 medium (150g)", calories: 59, protein: 1.4, carbs: 14, fat: 0.4, fiber: 2.3, sugar: 13, sodium: 0, cholesterol: 0 },
    { id: 111, name: "Pear", brand: "Generic", category: "fruits", emoji: "🍐", serving: "1 medium (178g)", calories: 102, protein: 0.6, carbs: 27, fat: 0.2, fiber: 5.5, sugar: 17, sodium: 2, cholesterol: 0 },
    { id: 112, name: "Kiwi", brand: "Generic", category: "fruits", emoji: "🥝", serving: "1 medium (69g)", calories: 42, protein: 0.8, carbs: 10, fat: 0.4, fiber: 2.1, sugar: 6.2, sodium: 2, cholesterol: 0 },
    { id: 113, name: "Cherries", brand: "Generic", category: "fruits", emoji: "🍒", serving: "1 cup (138g)", calories: 87, protein: 1.5, carbs: 22, fat: 0.3, fiber: 2.9, sugar: 18, sodium: 0, cholesterol: 0 },
    { id: 114, name: "Dried Dates", brand: "Generic", category: "fruits", emoji: "🌴", serving: "3 dates (72g)", calories: 200, protein: 1.8, carbs: 54, fat: 0.1, fiber: 4.8, sugar: 48, sodium: 1, cholesterol: 0 },
    { id: 115, name: "Raisins", brand: "Generic", category: "fruits", emoji: "🍇", serving: "1/4 cup (41g)", calories: 123, protein: 1.3, carbs: 33, fat: 0.2, fiber: 1.5, sugar: 25, sodium: 4, cholesterol: 0 },
    { id: 116, name: "Grapefruit", brand: "Generic", category: "fruits", emoji: "🍊", serving: "1/2 medium (128g)", calories: 52, protein: 0.9, carbs: 13, fat: 0.2, fiber: 2, sugar: 8.5, sodium: 0, cholesterol: 0 },
    { id: 117, name: "Papaya", brand: "Generic", category: "fruits", emoji: "🥭", serving: "1 cup cubed (140g)", calories: 55, protein: 0.9, carbs: 14, fat: 0.2, fiber: 2.5, sugar: 8.3, sodium: 4, cholesterol: 0 },
    { id: 118, name: "Pomegranate Seeds", brand: "Generic", category: "fruits", emoji: "🍎", serving: "1/2 cup (87g)", calories: 72, protein: 1.5, carbs: 16, fat: 1, fiber: 3.5, sugar: 12, sodium: 3, cholesterol: 0 },
    { id: 119, name: "Coconut (fresh)", brand: "Generic", category: "fruits", emoji: "🥥", serving: "1/3 cup (28g)", calories: 99, protein: 0.9, carbs: 4.3, fat: 9.4, fiber: 2.5, sugar: 1.7, sodium: 6, cholesterol: 0 },
    { id: 120, name: "Lemon", brand: "Generic", category: "fruits", emoji: "🍋", serving: "1 medium (58g)", calories: 17, protein: 0.6, carbs: 5.4, fat: 0.2, fiber: 1.6, sugar: 1.5, sodium: 1, cholesterol: 0 },

    // ==================== VEGETABLES ====================
    { id: 150, name: "Broccoli (cooked)", brand: "Generic", category: "vegetables", emoji: "🥦", serving: "1 cup (156g)", calories: 55, protein: 3.7, carbs: 11, fat: 0.6, fiber: 5.1, sugar: 2.2, sodium: 64, cholesterol: 0 },
    { id: 151, name: "Spinach (raw)", brand: "Generic", category: "vegetables", emoji: "🥬", serving: "1 cup (30g)", calories: 7, protein: 0.9, carbs: 1.1, fat: 0.1, fiber: 0.7, sugar: 0.1, sodium: 24, cholesterol: 0 },
    { id: 152, name: "Spinach (cooked)", brand: "Generic", category: "vegetables", emoji: "🥬", serving: "1 cup (180g)", calories: 41, protein: 5.3, carbs: 6.8, fat: 0.5, fiber: 4.3, sugar: 0.8, sodium: 126, cholesterol: 0 },
    { id: 153, name: "Kale (raw)", brand: "Generic", category: "vegetables", emoji: "🥬", serving: "1 cup (67g)", calories: 33, protein: 2.2, carbs: 6, fat: 0.6, fiber: 1.3, sugar: 0.8, sodium: 25, cholesterol: 0 },
    { id: 154, name: "Carrot", brand: "Generic", category: "vegetables", emoji: "🥕", serving: "1 medium (61g)", calories: 25, protein: 0.6, carbs: 6, fat: 0.1, fiber: 1.7, sugar: 2.9, sodium: 42, cholesterol: 0 },
    { id: 155, name: "Tomato", brand: "Generic", category: "vegetables", emoji: "🍅", serving: "1 medium (123g)", calories: 22, protein: 1.1, carbs: 4.8, fat: 0.2, fiber: 1.5, sugar: 3.2, sodium: 6, cholesterol: 0 },
    { id: 156, name: "Cucumber", brand: "Generic", category: "vegetables", emoji: "🥒", serving: "1 cup sliced (119g)", calories: 16, protein: 0.7, carbs: 3.1, fat: 0.2, fiber: 0.5, sugar: 1.7, sodium: 2, cholesterol: 0 },
    { id: 157, name: "Bell Pepper (red)", brand: "Generic", category: "vegetables", emoji: "🫑", serving: "1 medium (119g)", calories: 37, protein: 1.2, carbs: 7, fat: 0.4, fiber: 2.5, sugar: 5, sodium: 5, cholesterol: 0 },
    { id: 158, name: "Onion", brand: "Generic", category: "vegetables", emoji: "🧅", serving: "1 medium (110g)", calories: 44, protein: 1.2, carbs: 10, fat: 0.1, fiber: 1.9, sugar: 4.7, sodium: 4, cholesterol: 0 },
    { id: 159, name: "Corn (cooked)", brand: "Generic", category: "vegetables", emoji: "🌽", serving: "1 ear (102g)", calories: 99, protein: 3.5, carbs: 22, fat: 1.5, fiber: 2.7, sugar: 5, sodium: 1, cholesterol: 0 },
    { id: 160, name: "Green Beans", brand: "Generic", category: "vegetables", emoji: "🫘", serving: "1 cup (125g)", calories: 34, protein: 2, carbs: 8, fat: 0.1, fiber: 4, sugar: 1.5, sodium: 1, cholesterol: 0 },
    { id: 161, name: "Mushrooms (raw)", brand: "Generic", category: "vegetables", emoji: "🍄", serving: "1 cup sliced (70g)", calories: 15, protein: 2.2, carbs: 2.3, fat: 0.2, fiber: 0.7, sugar: 1.4, sodium: 4, cholesterol: 0 },
    { id: 162, name: "Zucchini", brand: "Generic", category: "vegetables", emoji: "🥒", serving: "1 cup sliced (113g)", calories: 19, protein: 1.4, carbs: 3.5, fat: 0.4, fiber: 1.1, sugar: 2.8, sodium: 10, cholesterol: 0 },
    { id: 163, name: "Cauliflower", brand: "Generic", category: "vegetables", emoji: "🥦", serving: "1 cup (100g)", calories: 25, protein: 1.9, carbs: 5, fat: 0.3, fiber: 2, sugar: 1.9, sodium: 30, cholesterol: 0 },
    { id: 164, name: "Asparagus", brand: "Generic", category: "vegetables", emoji: "🌿", serving: "6 spears (96g)", calories: 20, protein: 2.2, carbs: 3.7, fat: 0.1, fiber: 2, sugar: 1.2, sodium: 2, cholesterol: 0 },
    { id: 165, name: "Celery", brand: "Generic", category: "vegetables", emoji: "🌿", serving: "2 stalks (80g)", calories: 11, protein: 0.6, carbs: 2.4, fat: 0.1, fiber: 1.3, sugar: 1.1, sodium: 64, cholesterol: 0 },
    { id: 166, name: "Cabbage (raw)", brand: "Generic", category: "vegetables", emoji: "🥬", serving: "1 cup shredded (89g)", calories: 22, protein: 1.1, carbs: 5.2, fat: 0.1, fiber: 2.2, sugar: 2.8, sodium: 16, cholesterol: 0 },
    { id: 167, name: "Brussels Sprouts", brand: "Generic", category: "vegetables", emoji: "🥬", serving: "1 cup (88g)", calories: 38, protein: 3, carbs: 8, fat: 0.3, fiber: 3.3, sugar: 1.9, sodium: 22, cholesterol: 0 },
    { id: 168, name: "Eggplant (cooked)", brand: "Generic", category: "vegetables", emoji: "🍆", serving: "1 cup diced (99g)", calories: 35, protein: 0.8, carbs: 9, fat: 0.2, fiber: 2.5, sugar: 3.2, sodium: 1, cholesterol: 0 },
    { id: 169, name: "Lettuce (romaine)", brand: "Generic", category: "vegetables", emoji: "🥬", serving: "1 cup shredded (47g)", calories: 8, protein: 0.6, carbs: 1.5, fat: 0.1, fiber: 1, sugar: 0.6, sodium: 4, cholesterol: 0 },
    { id: 170, name: "Mixed Salad Greens", brand: "Generic", category: "vegetables", emoji: "🥗", serving: "2 cups (85g)", calories: 15, protein: 1.3, carbs: 2.4, fat: 0.2, fiber: 1.5, sugar: 0.5, sodium: 40, cholesterol: 0 },

    // ==================== DAIRY ====================
    { id: 200, name: "Whole Milk", brand: "Generic", category: "dairy", emoji: "🥛", serving: "1 cup (244ml)", calories: 149, protein: 8, carbs: 12, fat: 8, fiber: 0, sugar: 12, sodium: 105, cholesterol: 24 },
    { id: 201, name: "Skim Milk", brand: "Generic", category: "dairy", emoji: "🥛", serving: "1 cup (245ml)", calories: 83, protein: 8.3, carbs: 12, fat: 0.2, fiber: 0, sugar: 12, sodium: 103, cholesterol: 5 },
    { id: 202, name: "Cheddar Cheese", brand: "Generic", category: "dairy", emoji: "🧀", serving: "1 oz (28g)", calories: 113, protein: 7, carbs: 0.4, fat: 9.3, fiber: 0, sugar: 0.1, sodium: 176, cholesterol: 29 },
    { id: 203, name: "Mozzarella Cheese", brand: "Generic", category: "dairy", emoji: "🧀", serving: "1 oz (28g)", calories: 85, protein: 6.3, carbs: 0.7, fat: 6.3, fiber: 0, sugar: 0.3, sodium: 138, cholesterol: 22 },
    { id: 204, name: "Greek Yogurt (plain, 0%)", brand: "Generic", category: "dairy", emoji: "🥛", serving: "1 cup (245g)", calories: 130, protein: 23, carbs: 9, fat: 0.7, fiber: 0, sugar: 7, sodium: 92, cholesterol: 10 },
    { id: 205, name: "Greek Yogurt (2%)", brand: "Generic", category: "dairy", emoji: "🥛", serving: "1 cup (245g)", calories: 170, protein: 23, carbs: 10, fat: 4.5, fiber: 0, sugar: 8, sodium: 95, cholesterol: 20 },
    { id: 206, name: "Regular Yogurt (plain)", brand: "Generic", category: "dairy", emoji: "🥛", serving: "1 cup (245g)", calories: 149, protein: 8.5, carbs: 17, fat: 8, fiber: 0, sugar: 17, sodium: 113, cholesterol: 32 },
    { id: 207, name: "Butter", brand: "Generic", category: "dairy", emoji: "🧈", serving: "1 tbsp (14g)", calories: 102, protein: 0.1, carbs: 0, fat: 11.5, fiber: 0, sugar: 0, sodium: 2, cholesterol: 31 },
    { id: 208, name: "Cream Cheese", brand: "Generic", category: "dairy", emoji: "🧀", serving: "2 tbsp (29g)", calories: 99, protein: 1.7, carbs: 1.6, fat: 9.8, fiber: 0, sugar: 0.7, sodium: 85, cholesterol: 29 },
    { id: 209, name: "Parmesan Cheese", brand: "Generic", category: "dairy", emoji: "🧀", serving: "1 tbsp (5g)", calories: 21, protein: 1.4, carbs: 0.2, fat: 1.4, fiber: 0, sugar: 0, sodium: 76, cholesterol: 4 },
    { id: 210, name: "Almond Milk (unsweetened)", brand: "Generic", category: "dairy", emoji: "🥛", serving: "1 cup (240ml)", calories: 30, protein: 1, carbs: 1, fat: 2.5, fiber: 0, sugar: 0, sodium: 170, cholesterol: 0 },
    { id: 211, name: "Oat Milk", brand: "Generic", category: "dairy", emoji: "🥛", serving: "1 cup (240ml)", calories: 120, protein: 3, carbs: 16, fat: 5, fiber: 2, sugar: 7, sodium: 100, cholesterol: 0 },
    { id: 212, name: "Soy Milk", brand: "Generic", category: "dairy", emoji: "🥛", serving: "1 cup (240ml)", calories: 80, protein: 7, carbs: 4, fat: 4, fiber: 1, sugar: 1, sodium: 75, cholesterol: 0 },
    { id: 213, name: "Heavy Cream", brand: "Generic", category: "dairy", emoji: "🥛", serving: "1 tbsp (15ml)", calories: 51, protein: 0.4, carbs: 0.4, fat: 5.4, fiber: 0, sugar: 0.4, sodium: 6, cholesterol: 17 },
    { id: 214, name: "Swiss Cheese", brand: "Generic", category: "dairy", emoji: "🧀", serving: "1 oz (28g)", calories: 108, protein: 7.6, carbs: 1.5, fat: 7.9, fiber: 0, sugar: 0, sodium: 53, cholesterol: 26 },
    { id: 215, name: "Feta Cheese", brand: "Generic", category: "dairy", emoji: "🧀", serving: "1 oz (28g)", calories: 75, protein: 4, carbs: 1.2, fat: 6, fiber: 0, sugar: 1.2, sodium: 316, cholesterol: 25 },

    // ==================== BEVERAGES ====================
    { id: 250, name: "Black Coffee", brand: "Generic", category: "beverages", emoji: "☕", serving: "1 cup (237ml)", calories: 2, protein: 0.3, carbs: 0, fat: 0, fiber: 0, sugar: 0, sodium: 5, cholesterol: 0 },
    { id: 251, name: "Coffee with Milk & Sugar", brand: "Generic", category: "beverages", emoji: "☕", serving: "1 cup (240ml)", calories: 67, protein: 1, carbs: 11, fat: 2, fiber: 0, sugar: 10, sodium: 22, cholesterol: 5 },
    { id: 252, name: "Cappuccino", brand: "Generic", category: "beverages", emoji: "☕", serving: "12 oz (355ml)", calories: 120, protein: 6, carbs: 10, fat: 6, fiber: 0, sugar: 10, sodium: 80, cholesterol: 25 },
    { id: 253, name: "Latte (whole milk)", brand: "Starbucks", category: "beverages", emoji: "☕", serving: "16 oz (473ml)", calories: 190, protein: 10, carbs: 15, fat: 7, fiber: 0, sugar: 14, sodium: 115, cholesterol: 25 },
    { id: 254, name: "Green Tea", brand: "Generic", category: "beverages", emoji: "🍵", serving: "1 cup (237ml)", calories: 2, protein: 0.5, carbs: 0, fat: 0, fiber: 0, sugar: 0, sodium: 2, cholesterol: 0 },
    { id: 255, name: "Orange Juice", brand: "Generic", category: "beverages", emoji: "🧃", serving: "1 cup (248ml)", calories: 112, protein: 1.7, carbs: 26, fat: 0.5, fiber: 0.5, sugar: 21, sodium: 2, cholesterol: 0 },
    { id: 256, name: "Apple Juice", brand: "Generic", category: "beverages", emoji: "🧃", serving: "1 cup (248ml)", calories: 114, protein: 0.3, carbs: 28, fat: 0.3, fiber: 0.5, sugar: 24, sodium: 10, cholesterol: 0 },
    { id: 257, name: "Coca-Cola", brand: "Coca-Cola", category: "beverages", emoji: "🥤", serving: "1 can (355ml)", calories: 140, protein: 0, carbs: 39, fat: 0, fiber: 0, sugar: 39, sodium: 45, cholesterol: 0 },
    { id: 258, name: "Coca-Cola Zero", brand: "Coca-Cola", category: "beverages", emoji: "🥤", serving: "1 can (355ml)", calories: 0, protein: 0, carbs: 0, fat: 0, fiber: 0, sugar: 0, sodium: 40, cholesterol: 0 },
    { id: 259, name: "Protein Shake", brand: "Generic", category: "beverages", emoji: "🥤", serving: "1 bottle (414ml)", calories: 160, protein: 30, carbs: 6, fat: 2.5, fiber: 1, sugar: 2, sodium: 220, cholesterol: 10 },
    { id: 260, name: "Smoothie (Mixed Berry)", brand: "Generic", category: "beverages", emoji: "🥤", serving: "16 oz (473ml)", calories: 230, protein: 4, carbs: 52, fat: 1.5, fiber: 5, sugar: 42, sodium: 15, cholesterol: 0 },
    { id: 261, name: "Beer (regular)", brand: "Generic", category: "beverages", emoji: "🍺", serving: "12 oz (355ml)", calories: 153, protein: 1.6, carbs: 13, fat: 0, fiber: 0, sugar: 0, sodium: 14, cholesterol: 0 },
    { id: 262, name: "Red Wine", brand: "Generic", category: "beverages", emoji: "🍷", serving: "5 oz (148ml)", calories: 125, protein: 0.1, carbs: 3.8, fat: 0, fiber: 0, sugar: 0.9, sodium: 6, cholesterol: 0 },
    { id: 263, name: "Coconut Water", brand: "Generic", category: "beverages", emoji: "🥥", serving: "1 cup (240ml)", calories: 46, protein: 1.7, carbs: 9, fat: 0.5, fiber: 2.6, sugar: 6, sodium: 252, cholesterol: 0 },
    { id: 264, name: "Sports Drink (Gatorade)", brand: "Gatorade", category: "beverages", emoji: "🥤", serving: "20 oz (591ml)", calories: 140, protein: 0, carbs: 36, fat: 0, fiber: 0, sugar: 34, sodium: 270, cholesterol: 0 },
    { id: 265, name: "Chai Tea Latte", brand: "Generic", category: "beverages", emoji: "🍵", serving: "16 oz (473ml)", calories: 240, protein: 8, carbs: 42, fat: 4.5, fiber: 0, sugar: 40, sodium: 115, cholesterol: 15 },

    // ==================== INDIAN DRINKS ====================
    { id: 266, name: "Masala Chai", brand: "Indian Homemade", category: "indian-drinks", emoji: "🍵", serving: "1 cup (150ml)", calories: 95, protein: 2.2, carbs: 12, fat: 4, fiber: 0.2, sugar: 10, sodium: 32, cholesterol: 12 },
    { id: 267, name: "Adrak Chai (Ginger Tea)", brand: "Indian Homemade", category: "indian-drinks", emoji: "🍵", serving: "1 cup (150ml)", calories: 90, protein: 2, carbs: 11, fat: 3.8, fiber: 0.2, sugar: 9, sodium: 30, cholesterol: 11 },
    { id: 268, name: "Elaichi Chai (Cardamom Tea)", brand: "Indian Homemade", category: "indian-drinks", emoji: "🍵", serving: "1 cup (150ml)", calories: 92, protein: 2.1, carbs: 11.5, fat: 3.9, fiber: 0.1, sugar: 9.5, sodium: 31, cholesterol: 12 },
    { id: 269, name: "Cutting Chai", brand: "Tea Stall", category: "indian-drinks", emoji: "🍵", serving: "1 glass (90ml)", calories: 58, protein: 1.2, carbs: 7.5, fat: 2.5, fiber: 0.1, sugar: 6.2, sodium: 19, cholesterol: 7 },
    { id: 270, name: "South Indian Filter Coffee", brand: "Indian Homemade", category: "indian-drinks", emoji: "☕", serving: "1 tumbler (150ml)", calories: 88, protein: 2.5, carbs: 11, fat: 3.4, fiber: 0, sugar: 9, sodium: 28, cholesterol: 10 },
    { id: 271, name: "Cold Coffee (Indian Style)", brand: "Cafe", category: "indian-drinks", emoji: "☕", serving: "1 glass (250ml)", calories: 190, protein: 5, carbs: 28, fat: 6.5, fiber: 0, sugar: 24, sodium: 85, cholesterol: 24 },
    { id: 272, name: "Lassi (Sweet)", brand: "Indian Homemade", category: "indian-drinks", emoji: "🥛", serving: "1 glass (250ml)", calories: 180, protein: 6, carbs: 28, fat: 5, fiber: 0, sugar: 24, sodium: 95, cholesterol: 18 },
    { id: 273, name: "Lassi (Salted)", brand: "Indian Homemade", category: "indian-drinks", emoji: "🥛", serving: "1 glass (250ml)", calories: 112, protein: 6, carbs: 12, fat: 4, fiber: 0, sugar: 10, sodium: 360, cholesterol: 16 },
    { id: 274, name: "Mango Lassi", brand: "Indian Homemade", category: "indian-drinks", emoji: "🥭", serving: "1 glass (250ml)", calories: 220, protein: 7, carbs: 35, fat: 5.5, fiber: 1.2, sugar: 30, sodium: 102, cholesterol: 20 },
    { id: 275, name: "Chaas / Buttermilk", brand: "Indian Homemade", category: "indian-drinks", emoji: "🥛", serving: "1 glass (240ml)", calories: 60, protein: 3.2, carbs: 5, fat: 3, fiber: 0, sugar: 4.5, sodium: 240, cholesterol: 9 },
    { id: 276, name: "Masala Chaas", brand: "Indian Homemade", category: "indian-drinks", emoji: "🥛", serving: "1 glass (240ml)", calories: 64, protein: 3.3, carbs: 5.2, fat: 3.2, fiber: 0.2, sugar: 4.6, sodium: 290, cholesterol: 9 },
    { id: 277, name: "Jaljeera", brand: "Indian Homemade", category: "indian-drinks", emoji: "🧃", serving: "1 glass (240ml)", calories: 42, protein: 0.8, carbs: 9, fat: 0.3, fiber: 0.7, sugar: 6, sodium: 310, cholesterol: 0 },
    { id: 278, name: "Nimbu Pani", brand: "Indian Homemade", category: "indian-drinks", emoji: "🍋", serving: "1 glass (250ml)", calories: 74, protein: 0.3, carbs: 18, fat: 0.1, fiber: 0.2, sugar: 16, sodium: 45, cholesterol: 0 },
    { id: 279, name: "Shikanji", brand: "Indian Homemade", category: "indian-drinks", emoji: "🍋", serving: "1 glass (250ml)", calories: 82, protein: 0.4, carbs: 20, fat: 0.1, fiber: 0.3, sugar: 18, sodium: 48, cholesterol: 0 },
    { id: 280, name: "Aam Panna", brand: "Indian Homemade", category: "indian-drinks", emoji: "🥭", serving: "1 glass (250ml)", calories: 110, protein: 0.5, carbs: 27, fat: 0.2, fiber: 0.8, sugar: 24, sodium: 70, cholesterol: 0 },
    { id: 281, name: "Sugarcane Juice", brand: "Fresh Juice Stall", category: "indian-drinks", emoji: "🧃", serving: "1 glass (250ml)", calories: 183, protein: 0.2, carbs: 45, fat: 0, fiber: 0.2, sugar: 42, sodium: 22, cholesterol: 0 },
    { id: 282, name: "Tender Coconut Water", brand: "Fresh", category: "indian-drinks", emoji: "🥥", serving: "1 glass (240ml)", calories: 46, protein: 1.7, carbs: 9, fat: 0.5, fiber: 2.6, sugar: 6, sodium: 252, cholesterol: 0 },
    { id: 283, name: "Badam Milk", brand: "Indian Homemade", category: "indian-drinks", emoji: "🥛", serving: "1 glass (250ml)", calories: 210, protein: 7.5, carbs: 22, fat: 10, fiber: 1.5, sugar: 18, sodium: 110, cholesterol: 20 },
    { id: 284, name: "Kesar Milk", brand: "Indian Homemade", category: "indian-drinks", emoji: "🥛", serving: "1 glass (250ml)", calories: 198, protein: 7, carbs: 21, fat: 9, fiber: 0, sugar: 17, sodium: 98, cholesterol: 18 },
    { id: 285, name: "Rose Milk", brand: "Indian Homemade", category: "indian-drinks", emoji: "🥛", serving: "1 glass (250ml)", calories: 165, protein: 6, carbs: 22, fat: 5.5, fiber: 0, sugar: 20, sodium: 92, cholesterol: 16 },
    { id: 286, name: "Rooh Afza Sharbat", brand: "Hamdard", category: "indian-drinks", emoji: "🧃", serving: "1 glass (250ml)", calories: 132, protein: 0, carbs: 33, fat: 0, fiber: 0, sugar: 32, sodium: 20, cholesterol: 0 },
    { id: 287, name: "Rasna (Prepared)", brand: "Rasna", category: "indian-drinks", emoji: "🧃", serving: "1 glass (250ml)", calories: 96, protein: 0, carbs: 24, fat: 0, fiber: 0, sugar: 23, sodium: 18, cholesterol: 0 },
    { id: 288, name: "Frooti Mango Drink", brand: "Parle Agro", category: "indian-drinks", emoji: "🥭", serving: "1 pack (200ml)", calories: 126, protein: 0, carbs: 31, fat: 0, fiber: 0.3, sugar: 30, sodium: 20, cholesterol: 0 },
    { id: 289, name: "Maaza Mango Drink", brand: "Coca-Cola India", category: "indian-drinks", emoji: "🥭", serving: "1 bottle (250ml)", calories: 150, protein: 0.2, carbs: 37, fat: 0, fiber: 0.4, sugar: 35, sodium: 24, cholesterol: 0 },
    { id: 290, name: "Slice Mango Drink", brand: "PepsiCo India", category: "indian-drinks", emoji: "🥭", serving: "1 bottle (250ml)", calories: 148, protein: 0.2, carbs: 36, fat: 0, fiber: 0.3, sugar: 34, sodium: 22, cholesterol: 0 },
    { id: 291, name: "Thums Up", brand: "Coca-Cola India", category: "indian-drinks", emoji: "🥤", serving: "1 bottle (250ml)", calories: 110, protein: 0, carbs: 27, fat: 0, fiber: 0, sugar: 27, sodium: 34, cholesterol: 0 },
    { id: 292, name: "Limca", brand: "Coca-Cola India", category: "indian-drinks", emoji: "🥤", serving: "1 bottle (250ml)", calories: 105, protein: 0, carbs: 26, fat: 0, fiber: 0, sugar: 26, sodium: 42, cholesterol: 0 },
    { id: 293, name: "Appy Fizz", brand: "Parle Agro", category: "indian-drinks", emoji: "🍏", serving: "1 can (250ml)", calories: 122, protein: 0, carbs: 30, fat: 0, fiber: 0, sugar: 29, sodium: 20, cholesterol: 0 },
    { id: 294, name: "Paper Boat Aamras", brand: "Paper Boat", category: "indian-drinks", emoji: "🥭", serving: "1 pouch (200ml)", calories: 126, protein: 0.4, carbs: 31, fat: 0.1, fiber: 0.8, sugar: 27, sodium: 16, cholesterol: 0 },
    { id: 295, name: "Paper Boat Jaljeera", brand: "Paper Boat", category: "indian-drinks", emoji: "🧃", serving: "1 pouch (200ml)", calories: 68, protein: 0.3, carbs: 16, fat: 0.1, fiber: 0.5, sugar: 14, sodium: 190, cholesterol: 0 },
    { id: 296, name: "Bournvita Milk", brand: "Bournvita", category: "indian-drinks", emoji: "🥛", serving: "1 glass (200ml)", calories: 170, protein: 6, carbs: 24, fat: 5.5, fiber: 1.2, sugar: 18, sodium: 130, cholesterol: 14 },
    { id: 297, name: "Horlicks Milk", brand: "Horlicks", category: "indian-drinks", emoji: "🥛", serving: "1 glass (200ml)", calories: 162, protein: 6.2, carbs: 22, fat: 5, fiber: 1, sugar: 16, sodium: 125, cholesterol: 14 },
    { id: 298, name: "Boost Milk", brand: "Boost", category: "indian-drinks", emoji: "🥛", serving: "1 glass (200ml)", calories: 168, protein: 6.1, carbs: 23, fat: 5.3, fiber: 1, sugar: 17, sodium: 126, cholesterol: 14 },
    { id: 299, name: "Complan Milk", brand: "Complan", category: "indian-drinks", emoji: "🥛", serving: "1 glass (200ml)", calories: 180, protein: 7.2, carbs: 24, fat: 6, fiber: 1.2, sugar: 18, sodium: 130, cholesterol: 15 },
    { id: 530, name: "Amul Kool Kesar", brand: "Amul", category: "indian-drinks", emoji: "🥛", serving: "1 bottle (200ml)", calories: 146, protein: 5.2, carbs: 19, fat: 5.3, fiber: 0, sugar: 17, sodium: 96, cholesterol: 14 },
    { id: 531, name: "Amul Kool Badam", brand: "Amul", category: "indian-drinks", emoji: "🥛", serving: "1 bottle (200ml)", calories: 154, protein: 5.4, carbs: 20, fat: 5.8, fiber: 0.4, sugar: 18, sodium: 100, cholesterol: 14 },
    { id: 532, name: "Amul Kool Coffee", brand: "Amul", category: "indian-drinks", emoji: "☕", serving: "1 bottle (200ml)", calories: 142, protein: 5, carbs: 18, fat: 5.4, fiber: 0, sugar: 16, sodium: 94, cholesterol: 14 },
    { id: 533, name: "Amul Masti Spiced Buttermilk", brand: "Amul", category: "indian-drinks", emoji: "🥛", serving: "1 pack (200ml)", calories: 54, protein: 2.8, carbs: 4.2, fat: 2.8, fiber: 0, sugar: 3.8, sodium: 240, cholesterol: 8 },
    { id: 534, name: "Amul Lassi", brand: "Amul", category: "indian-drinks", emoji: "🥛", serving: "1 pack (200ml)", calories: 128, protein: 5.2, carbs: 18, fat: 4.1, fiber: 0, sugar: 16, sodium: 90, cholesterol: 14 },
    { id: 535, name: "Mother Dairy Classic Lassi", brand: "Mother Dairy", category: "indian-drinks", emoji: "🥛", serving: "1 bottle (200ml)", calories: 132, protein: 5, carbs: 19, fat: 4.2, fiber: 0, sugar: 17, sodium: 92, cholesterol: 14 },
    { id: 536, name: "Mother Dairy Masala Chaach", brand: "Mother Dairy", category: "indian-drinks", emoji: "🥛", serving: "1 bottle (200ml)", calories: 48, protein: 2.6, carbs: 4, fat: 2.3, fiber: 0, sugar: 3.6, sodium: 220, cholesterol: 7 },
    { id: 537, name: "Paper Boat Aam Panna", brand: "Paper Boat", category: "indian-drinks", emoji: "🥭", serving: "1 pouch (200ml)", calories: 82, protein: 0.2, carbs: 20, fat: 0, fiber: 0.3, sugar: 18, sodium: 68, cholesterol: 0 },
    { id: 538, name: "Paper Boat Nimbu Pani", brand: "Paper Boat", category: "indian-drinks", emoji: "🍋", serving: "1 pouch (200ml)", calories: 74, protein: 0.1, carbs: 18, fat: 0, fiber: 0.1, sugar: 16, sodium: 60, cholesterol: 0 },
    { id: 539, name: "Paper Boat Coconut Water", brand: "Paper Boat", category: "indian-drinks", emoji: "🥥", serving: "1 pack (200ml)", calories: 38, protein: 1.2, carbs: 8.2, fat: 0.3, fiber: 1.8, sugar: 5.2, sodium: 190, cholesterol: 0 },
    { id: 540, name: "Paper Boat Golgappe Ka Pani", brand: "Paper Boat", category: "indian-drinks", emoji: "🧃", serving: "1 pouch (200ml)", calories: 44, protein: 0.5, carbs: 10, fat: 0.2, fiber: 0.4, sugar: 7, sodium: 260, cholesterol: 0 },
    { id: 541, name: "Real Mixed Fruit Juice", brand: "Real", category: "indian-drinks", emoji: "🧃", serving: "1 glass (200ml)", calories: 92, protein: 0.5, carbs: 22, fat: 0.1, fiber: 0.4, sugar: 20, sodium: 18, cholesterol: 0 },
    { id: 542, name: "Real Orange Juice", brand: "Real", category: "indian-drinks", emoji: "🍊", serving: "1 glass (200ml)", calories: 88, protein: 0.6, carbs: 21, fat: 0.1, fiber: 0.3, sugar: 19, sodium: 16, cholesterol: 0 },
    { id: 543, name: "Real Guava Juice", brand: "Real", category: "indian-drinks", emoji: "🧃", serving: "1 glass (200ml)", calories: 96, protein: 0.8, carbs: 23, fat: 0.1, fiber: 0.6, sugar: 21, sodium: 18, cholesterol: 0 },
    { id: 544, name: "Real Litchi Juice", brand: "Real", category: "indian-drinks", emoji: "🧃", serving: "1 glass (200ml)", calories: 100, protein: 0.2, carbs: 24, fat: 0.1, fiber: 0.2, sugar: 23, sodium: 14, cholesterol: 0 },
    { id: 545, name: "Tropicana Mixed Fruit Delight", brand: "Tropicana", category: "indian-drinks", emoji: "🧃", serving: "1 glass (200ml)", calories: 94, protein: 0.4, carbs: 23, fat: 0.1, fiber: 0.3, sugar: 21, sodium: 20, cholesterol: 0 },
    { id: 546, name: "Tropicana Orange Delight", brand: "Tropicana", category: "indian-drinks", emoji: "🍊", serving: "1 glass (200ml)", calories: 90, protein: 0.5, carbs: 22, fat: 0.1, fiber: 0.2, sugar: 20, sodium: 18, cholesterol: 0 },
    { id: 547, name: "Minute Maid Pulpy Orange", brand: "Coca-Cola India", category: "indian-drinks", emoji: "🍊", serving: "1 bottle (250ml)", calories: 118, protein: 0.4, carbs: 29, fat: 0, fiber: 0.4, sugar: 27, sodium: 22, cholesterol: 0 },
    { id: 548, name: "Minute Maid Apple Sparkle", brand: "Coca-Cola India", category: "indian-drinks", emoji: "🍏", serving: "1 bottle (250ml)", calories: 124, protein: 0.1, carbs: 31, fat: 0, fiber: 0.1, sugar: 29, sodium: 24, cholesterol: 0 },
    { id: 549, name: "Sting Energy Drink", brand: "PepsiCo India", category: "indian-drinks", emoji: "⚡", serving: "1 can (250ml)", calories: 112, protein: 0, carbs: 28, fat: 0, fiber: 0, sugar: 27, sodium: 95, cholesterol: 0 },
    { id: 550, name: "Red Bull Energy Drink", brand: "Red Bull India", category: "indian-drinks", emoji: "⚡", serving: "1 can (250ml)", calories: 112, protein: 0, carbs: 27, fat: 0, fiber: 0, sugar: 27, sodium: 105, cholesterol: 0 },
    { id: 551, name: "Glucon-D Orange Drink", brand: "Glucon-D", category: "indian-drinks", emoji: "🧃", serving: "1 glass (200ml)", calories: 74, protein: 0, carbs: 18, fat: 0, fiber: 0, sugar: 17, sodium: 42, cholesterol: 0 },
    { id: 552, name: "Tang Orange Drink", brand: "Tang", category: "indian-drinks", emoji: "🍊", serving: "1 glass (200ml)", calories: 78, protein: 0, carbs: 19, fat: 0, fiber: 0, sugar: 18, sodium: 28, cholesterol: 0 },
    { id: 553, name: "Bru Instant Coffee with Milk", brand: "Bru", category: "indian-drinks", emoji: "☕", serving: "1 cup (180ml)", calories: 82, protein: 2.6, carbs: 10, fat: 3.2, fiber: 0, sugar: 8, sodium: 34, cholesterol: 10 },
    { id: 554, name: "Nescafe Sunrise Coffee with Milk", brand: "Nescafe", category: "indian-drinks", emoji: "☕", serving: "1 cup (180ml)", calories: 84, protein: 2.5, carbs: 10.5, fat: 3.3, fiber: 0, sugar: 8.5, sodium: 35, cholesterol: 10 },
    { id: 555, name: "Bovonto", brand: "Kalimark", category: "indian-drinks", emoji: "🥤", serving: "1 bottle (250ml)", calories: 118, protein: 0, carbs: 29, fat: 0, fiber: 0, sugar: 28, sodium: 26, cholesterol: 0 },
    { id: 556, name: "Sosyo", brand: "Hajoori", category: "indian-drinks", emoji: "🥤", serving: "1 bottle (250ml)", calories: 120, protein: 0, carbs: 30, fat: 0, fiber: 0, sugar: 29, sodium: 24, cholesterol: 0 },
    { id: 557, name: "Jeera Masala Soda", brand: "Generic", category: "indian-drinks", emoji: "🥤", serving: "1 bottle (250ml)", calories: 82, protein: 0, carbs: 20, fat: 0, fiber: 0, sugar: 18, sodium: 70, cholesterol: 0 },
    { id: 558, name: "Smoodh Chocolate Milk", brand: "Parle Agro", category: "indian-drinks", emoji: "🥛", serving: "1 bottle (180ml)", calories: 148, protein: 4.2, carbs: 21, fat: 5.2, fiber: 0.3, sugar: 18, sodium: 88, cholesterol: 12 },
    { id: 559, name: "Smoodh Hazelnut Milk", brand: "Parle Agro", category: "indian-drinks", emoji: "🥛", serving: "1 bottle (180ml)", calories: 152, protein: 4.1, carbs: 22, fat: 5.4, fiber: 0.3, sugar: 19, sodium: 90, cholesterol: 12 },
    { id: 560, name: "Amul Tru Mango", brand: "Amul", category: "indian-drinks", emoji: "🥭", serving: "1 bottle (200ml)", calories: 134, protein: 4.8, carbs: 20, fat: 4.2, fiber: 0.2, sugar: 18, sodium: 92, cholesterol: 13 },

    // ==================== SNACKS ====================
    { id: 300, name: "Almonds", brand: "Generic", category: "snacks", emoji: "🥜", serving: "1 oz (28g, ~23 nuts)", calories: 164, protein: 6, carbs: 6, fat: 14, fiber: 3.5, sugar: 1.2, sodium: 0, cholesterol: 0 },
    { id: 301, name: "Peanuts", brand: "Generic", category: "snacks", emoji: "🥜", serving: "1 oz (28g)", calories: 161, protein: 7, carbs: 4.6, fat: 14, fiber: 2.4, sugar: 1.3, sodium: 5, cholesterol: 0 },
    { id: 302, name: "Walnuts", brand: "Generic", category: "snacks", emoji: "🥜", serving: "1 oz (28g)", calories: 185, protein: 4.3, carbs: 3.9, fat: 18, fiber: 1.9, sugar: 0.7, sodium: 1, cholesterol: 0 },
    { id: 303, name: "Peanut Butter", brand: "Generic", category: "snacks", emoji: "🥜", serving: "2 tbsp (32g)", calories: 188, protein: 7, carbs: 7, fat: 16, fiber: 1.6, sugar: 3, sodium: 136, cholesterol: 0 },
    { id: 304, name: "Almond Butter", brand: "Generic", category: "snacks", emoji: "🥜", serving: "2 tbsp (32g)", calories: 196, protein: 6.8, carbs: 6, fat: 18, fiber: 3.3, sugar: 2, sodium: 73, cholesterol: 0 },
    { id: 305, name: "Dark Chocolate (70%)", brand: "Generic", category: "snacks", emoji: "🍫", serving: "1 oz (28g)", calories: 170, protein: 2.2, carbs: 13, fat: 12, fiber: 3.1, sugar: 7, sodium: 6, cholesterol: 0 },
    { id: 306, name: "Milk Chocolate", brand: "Generic", category: "snacks", emoji: "🍫", serving: "1 oz (28g)", calories: 153, protein: 2.2, carbs: 17, fat: 8.7, fiber: 0.9, sugar: 15, sodium: 24, cholesterol: 6 },
    { id: 307, name: "Chips (Lay's Classic)", brand: "Lay's", category: "snacks", emoji: "🍟", serving: "1 oz (28g)", calories: 160, protein: 2, carbs: 15, fat: 10, fiber: 1, sugar: 0.5, sodium: 170, cholesterol: 0 },
    { id: 308, name: "Tortilla Chips", brand: "Generic", category: "snacks", emoji: "🍟", serving: "1 oz (28g)", calories: 140, protein: 2, carbs: 19, fat: 7, fiber: 1.4, sugar: 0.3, sodium: 115, cholesterol: 0 },
    { id: 309, name: "Pretzels", brand: "Generic", category: "snacks", emoji: "🥨", serving: "1 oz (28g)", calories: 108, protein: 3, carbs: 22, fat: 1, fiber: 0.9, sugar: 0.7, sodium: 352, cholesterol: 0 },
    { id: 310, name: "Trail Mix", brand: "Generic", category: "snacks", emoji: "🥜", serving: "1/4 cup (40g)", calories: 173, protein: 5, carbs: 17, fat: 11, fiber: 2, sugar: 9, sodium: 65, cholesterol: 1 },
    { id: 311, name: "Granola Bar", brand: "Nature Valley", category: "snacks", emoji: "🍫", serving: "1 bar (42g)", calories: 190, protein: 4, carbs: 29, fat: 7, fiber: 2, sugar: 12, sodium: 160, cholesterol: 0 },
    { id: 312, name: "Protein Bar", brand: "Quest", category: "snacks", emoji: "🍫", serving: "1 bar (60g)", calories: 200, protein: 21, carbs: 22, fat: 8, fiber: 14, sugar: 1, sodium: 280, cholesterol: 5 },
    { id: 313, name: "Hummus", brand: "Generic", category: "snacks", emoji: "🫘", serving: "2 tbsp (30g)", calories: 70, protein: 2, carbs: 4, fat: 5, fiber: 1, sugar: 0, sodium: 130, cholesterol: 0 },
    { id: 314, name: "Guacamole", brand: "Generic", category: "snacks", emoji: "🥑", serving: "2 tbsp (30g)", calories: 47, protein: 0.6, carbs: 2.6, fat: 4, fiber: 1.8, sugar: 0.3, sodium: 115, cholesterol: 0 },
    { id: 315, name: "Mixed Nuts (roasted)", brand: "Generic", category: "snacks", emoji: "🥜", serving: "1 oz (28g)", calories: 172, protein: 5, carbs: 7, fat: 15, fiber: 2, sugar: 1.5, sodium: 96, cholesterol: 0 },
    { id: 316, name: "Dried Cranberries", brand: "Generic", category: "snacks", emoji: "🍇", serving: "1/4 cup (40g)", calories: 123, protein: 0.1, carbs: 33, fat: 0.5, fiber: 2.3, sugar: 29, sodium: 2, cholesterol: 0 },
    { id: 317, name: "Rice Crackers", brand: "Generic", category: "snacks", emoji: "🍘", serving: "10 crackers (30g)", calories: 120, protein: 2, carbs: 25, fat: 1.5, fiber: 0.3, sugar: 2, sodium: 200, cholesterol: 0 },
    { id: 318, name: "Cookie (Chocolate Chip)", brand: "Generic", category: "snacks", emoji: "🍪", serving: "1 cookie (40g)", calories: 190, protein: 2, carbs: 26, fat: 9, fiber: 1, sugar: 15, sodium: 120, cholesterol: 10 },
    { id: 319, name: "Ice Cream (Vanilla)", brand: "Generic", category: "snacks", emoji: "🍦", serving: "1/2 cup (66g)", calories: 137, protein: 2.3, carbs: 16, fat: 7.3, fiber: 0.5, sugar: 14, sodium: 53, cholesterol: 29 },
    { id: 320, name: "Donut (Glazed)", brand: "Generic", category: "snacks", emoji: "🍩", serving: "1 donut (60g)", calories: 253, protein: 3.7, carbs: 29, fat: 14, fiber: 0.7, sugar: 13, sodium: 185, cholesterol: 16 },

    // ==================== INDIAN PACKAGED SNACKS & BISCUITS ====================
    { id: 561, name: "Parle-G Biscuits", brand: "Parle", category: "indian-snacks", emoji: "🍪", serving: "4 biscuits (28g)", calories: 126, protein: 2, carbs: 21, fat: 3.6, fiber: 0.5, sugar: 6, sodium: 95, cholesterol: 0 },
    { id: 562, name: "Monaco Salted Crackers", brand: "Parle", category: "indian-snacks", emoji: "🍘", serving: "6 crackers (30g)", calories: 135, protein: 2.4, carbs: 20, fat: 5, fiber: 0.6, sugar: 1.2, sodium: 220, cholesterol: 0 },
    { id: 563, name: "Krackjack Biscuits", brand: "Parle", category: "indian-snacks", emoji: "🍪", serving: "4 biscuits (27g)", calories: 128, protein: 2, carbs: 18, fat: 5.5, fiber: 0.4, sugar: 5, sodium: 120, cholesterol: 0 },
    { id: 564, name: "Hide & Seek Chocolate Chip", brand: "Parle", category: "indian-snacks", emoji: "🍪", serving: "3 biscuits (33g)", calories: 168, protein: 2.2, carbs: 23, fat: 7.2, fiber: 0.8, sugar: 10, sodium: 105, cholesterol: 2 },
    { id: 565, name: "20-20 Butter Cookies", brand: "Parle", category: "indian-snacks", emoji: "🍪", serving: "4 biscuits (32g)", calories: 164, protein: 2, carbs: 21, fat: 8, fiber: 0.5, sugar: 7, sodium: 115, cholesterol: 3 },
    { id: 566, name: "Good Day Butter Cookies", brand: "Britannia", category: "indian-snacks", emoji: "🍪", serving: "3 biscuits (33g)", calories: 170, protein: 2, carbs: 22, fat: 8.4, fiber: 0.5, sugar: 8, sodium: 110, cholesterol: 4 },
    { id: 567, name: "Good Day Cashew Cookies", brand: "Britannia", category: "indian-snacks", emoji: "🍪", serving: "3 biscuits (33g)", calories: 173, protein: 2.3, carbs: 22, fat: 8.7, fiber: 0.6, sugar: 8, sodium: 108, cholesterol: 4 },
    { id: 568, name: "Marie Gold Biscuits", brand: "Britannia", category: "indian-snacks", emoji: "🍪", serving: "4 biscuits (24g)", calories: 108, protein: 1.7, carbs: 18, fat: 3.1, fiber: 0.4, sugar: 4.5, sodium: 88, cholesterol: 0 },
    { id: 569, name: "Tiger Glucose Biscuits", brand: "Britannia", category: "indian-snacks", emoji: "🍪", serving: "4 biscuits (28g)", calories: 126, protein: 1.8, carbs: 21, fat: 3.8, fiber: 0.4, sugar: 6.2, sodium: 96, cholesterol: 0 },
    { id: 570, name: "50-50 Maska Chaska", brand: "Britannia", category: "indian-snacks", emoji: "🍘", serving: "5 biscuits (33g)", calories: 162, protein: 2.5, carbs: 22, fat: 7, fiber: 0.7, sugar: 3, sodium: 220, cholesterol: 0 },
    { id: 571, name: "NutriChoice Digestive", brand: "Britannia", category: "indian-snacks", emoji: "🍪", serving: "3 biscuits (31g)", calories: 136, protein: 2.5, carbs: 21, fat: 4.8, fiber: 1.8, sugar: 5.2, sodium: 130, cholesterol: 0 },
    { id: 572, name: "Little Hearts", brand: "Britannia", category: "indian-snacks", emoji: "🥨", serving: "1 small pack (27g)", calories: 133, protein: 1.7, carbs: 18, fat: 5.8, fiber: 0.5, sugar: 8.5, sodium: 92, cholesterol: 0 },
    { id: 573, name: "Bourbon Biscuits", brand: "Britannia", category: "indian-snacks", emoji: "🍪", serving: "3 biscuits (34g)", calories: 165, protein: 2.2, carbs: 24, fat: 6.8, fiber: 0.9, sugar: 10, sodium: 118, cholesterol: 2 },
    { id: 574, name: "Jim Jam Biscuits", brand: "Britannia", category: "indian-snacks", emoji: "🍪", serving: "3 biscuits (32g)", calories: 154, protein: 1.8, carbs: 22, fat: 6.2, fiber: 0.5, sugar: 9, sodium: 105, cholesterol: 2 },
    { id: 575, name: "Dark Fantasy Choco Fills", brand: "Sunfeast", category: "indian-snacks", emoji: "🍪", serving: "2 cookies (30g)", calories: 154, protein: 2, carbs: 21, fat: 6.8, fiber: 0.8, sugar: 10, sodium: 95, cholesterol: 3 },
    { id: 576, name: "Sunfeast Mom's Magic Cashew", brand: "Sunfeast", category: "indian-snacks", emoji: "🍪", serving: "3 biscuits (30g)", calories: 151, protein: 2.1, carbs: 19, fat: 7.2, fiber: 0.6, sugar: 7, sodium: 100, cholesterol: 3 },
    { id: 577, name: "Sunfeast Farmlite Oats", brand: "Sunfeast", category: "indian-snacks", emoji: "🍪", serving: "3 biscuits (30g)", calories: 137, protein: 2.4, carbs: 20, fat: 5.1, fiber: 1.5, sugar: 5.5, sodium: 112, cholesterol: 0 },
    { id: 578, name: "Aloo Bhujia", brand: "Haldiram's", category: "indian-snacks", emoji: "🍟", serving: "1 small pack (35g)", calories: 195, protein: 3.2, carbs: 18, fat: 12, fiber: 2.1, sugar: 0.8, sodium: 310, cholesterol: 0 },
    { id: 579, name: "Bhujia Sev", brand: "Bikaji", category: "indian-snacks", emoji: "🍜", serving: "1 small pack (35g)", calories: 192, protein: 4, carbs: 17, fat: 12, fiber: 2, sugar: 0.7, sodium: 295, cholesterol: 0 },
    { id: 580, name: "Navratan Mixture", brand: "Haldiram's", category: "indian-snacks", emoji: "🥜", serving: "1 small pack (35g)", calories: 210, protein: 4.5, carbs: 18, fat: 13.5, fiber: 2.2, sugar: 2, sodium: 280, cholesterol: 0 },
    { id: 581, name: "Moong Dal", brand: "Haldiram's", category: "indian-snacks", emoji: "🫘", serving: "1 small pack (35g)", calories: 198, protein: 6.2, carbs: 15, fat: 12, fiber: 2, sugar: 0.4, sodium: 240, cholesterol: 0 },
    { id: 582, name: "Masala Peanuts", brand: "Haldiram's", category: "indian-snacks", emoji: "🥜", serving: "1 small pack (35g)", calories: 202, protein: 7, carbs: 10, fat: 15, fiber: 2.1, sugar: 1.2, sodium: 220, cholesterol: 0 },
    { id: 583, name: "Khatta Meetha", brand: "Bikaji", category: "indian-snacks", emoji: "🥜", serving: "1 small pack (35g)", calories: 184, protein: 3.5, carbs: 22, fat: 9.5, fiber: 1.4, sugar: 5.5, sodium: 260, cholesterol: 0 },
    { id: 584, name: "Banana Chips", brand: "MTR", category: "indian-snacks", emoji: "🍌", serving: "1 small pack (35g)", calories: 190, protein: 1.5, carbs: 20, fat: 11.5, fiber: 1.7, sugar: 4.5, sodium: 85, cholesterol: 0 },
    { id: 585, name: "Mad Angles Achaari Masti", brand: "Bingo!", category: "indian-snacks", emoji: "🔺", serving: "1 pack (32g)", calories: 164, protein: 2.4, carbs: 19, fat: 8.6, fiber: 1.1, sugar: 1.5, sodium: 235, cholesterol: 0 },
    { id: 586, name: "Tedhe Medhe", brand: "Bingo!", category: "indian-snacks", emoji: "🥨", serving: "1 pack (30g)", calories: 154, protein: 2.2, carbs: 18, fat: 8.2, fiber: 0.9, sugar: 1.4, sodium: 210, cholesterol: 0 },
    { id: 587, name: "Lay's Magic Masala", brand: "Lay's India", category: "indian-snacks", emoji: "🍟", serving: "1 pack (28g)", calories: 155, protein: 2, carbs: 15, fat: 10, fiber: 1.1, sugar: 0.6, sodium: 175, cholesterol: 0 },
    { id: 588, name: "Kurkure Masala Munch", brand: "Kurkure", category: "indian-snacks", emoji: "🌽", serving: "1 pack (28g)", calories: 152, protein: 2, carbs: 16, fat: 9, fiber: 0.9, sugar: 1.1, sodium: 230, cholesterol: 0 },
    { id: 589, name: "Kurkure Green Chutney Rajasthani Style", brand: "Kurkure", category: "indian-snacks", emoji: "🌽", serving: "1 pack (28g)", calories: 150, protein: 2, carbs: 16, fat: 8.8, fiber: 0.8, sugar: 1, sodium: 225, cholesterol: 0 },
    { id: 590, name: "Too Yumm! Multigrain Chips", brand: "Too Yumm!", category: "indian-snacks", emoji: "🍟", serving: "1 pack (25g)", calories: 118, protein: 2.6, carbs: 15, fat: 5.4, fiber: 1.8, sugar: 0.8, sodium: 170, cholesterol: 0 },
    { id: 591, name: "Balaji Wafers Masala Masti", brand: "Balaji", category: "indian-snacks", emoji: "🍟", serving: "1 pack (28g)", calories: 153, protein: 2, carbs: 16, fat: 9.2, fiber: 1, sugar: 0.7, sodium: 180, cholesterol: 0 },
    { id: 592, name: "Makhana Peri Peri", brand: "Open Secret", category: "indian-snacks", emoji: "🍿", serving: "1 pack (25g)", calories: 98, protein: 3.2, carbs: 13, fat: 3.8, fiber: 1.7, sugar: 0.6, sodium: 145, cholesterol: 0 },
    { id: 593, name: "Roasted Chana", brand: "Generic India", category: "indian-snacks", emoji: "🫘", serving: "1 pack (30g)", calories: 112, protein: 6.1, carbs: 18, fat: 1.8, fiber: 4.2, sugar: 1.5, sodium: 65, cholesterol: 0 },
    { id: 594, name: "Chikki (Peanut Jaggery)", brand: "Generic India", category: "indian-snacks", emoji: "🥜", serving: "1 bar (25g)", calories: 128, protein: 3.2, carbs: 14, fat: 6.5, fiber: 1.1, sugar: 9.5, sodium: 18, cholesterol: 0 },
    { id: 595, name: "Soya Sticks Chatpata", brand: "Too Yumm!", category: "indian-snacks", emoji: "🥨", serving: "1 pack (20g)", calories: 96, protein: 6.5, carbs: 8.2, fat: 4.2, fiber: 1.5, sugar: 0.8, sodium: 158, cholesterol: 0 },
    { id: 596, name: "Cream & Onion Rings", brand: "Bingo!", category: "indian-snacks", emoji: "🧅", serving: "1 pack (28g)", calories: 149, protein: 1.9, carbs: 16, fat: 8.8, fiber: 0.9, sugar: 1, sodium: 205, cholesterol: 0 },
    { id: 597, name: "Unibic Choco Chip Cookies", brand: "Unibic", category: "indian-snacks", emoji: "🍪", serving: "3 cookies (30g)", calories: 152, protein: 2, carbs: 20, fat: 7.2, fiber: 0.8, sugar: 9, sodium: 102, cholesterol: 3 },
    { id: 598, name: "Unibic Oatmeal Digestive", brand: "Unibic", category: "indian-snacks", emoji: "🍪", serving: "3 biscuits (30g)", calories: 136, protein: 2.4, carbs: 19, fat: 5.5, fiber: 1.6, sugar: 5.6, sodium: 112, cholesterol: 0 },
    { id: 599, name: "Baked Ragi Chips", brand: "Snackible", category: "indian-snacks", emoji: "🍟", serving: "1 pack (25g)", calories: 108, protein: 2.2, carbs: 14, fat: 4.8, fiber: 1.9, sugar: 0.7, sodium: 148, cholesterol: 0 },
    { id: 600, name: "Fox Nuts Himalayan Salt", brand: "Too Yumm!", category: "indian-snacks", emoji: "🍿", serving: "1 pack (20g)", calories: 82, protein: 2.8, carbs: 11, fat: 3, fiber: 1.3, sugar: 0.4, sodium: 120, cholesterol: 0 },

    // ==================== FAST FOOD ====================
    { id: 350, name: "Big Mac", brand: "McDonald's", category: "fast-food", emoji: "🍔", serving: "1 burger (215g)", calories: 550, protein: 25, carbs: 45, fat: 30, fiber: 3, sugar: 9, sodium: 1010, cholesterol: 80 },
    { id: 351, name: "Quarter Pounder with Cheese", brand: "McDonald's", category: "fast-food", emoji: "🍔", serving: "1 burger (202g)", calories: 520, protein: 30, carbs: 42, fat: 26, fiber: 2, sugar: 10, sodium: 1100, cholesterol: 95 },
    { id: 352, name: "Chicken McNuggets (6 pc)", brand: "McDonald's", category: "fast-food", emoji: "🍗", serving: "6 pieces (96g)", calories: 250, protein: 15, carbs: 15, fat: 15, fiber: 1, sugar: 0, sodium: 500, cholesterol: 35 },
    { id: 353, name: "McChicken", brand: "McDonald's", category: "fast-food", emoji: "🍔", serving: "1 sandwich (147g)", calories: 400, protein: 14, carbs: 40, fat: 21, fiber: 2, sugar: 5, sodium: 780, cholesterol: 40 },
    { id: 354, name: "Whopper", brand: "Burger King", category: "fast-food", emoji: "🍔", serving: "1 burger (291g)", calories: 657, protein: 28, carbs: 49, fat: 40, fiber: 2, sugar: 11, sodium: 911, cholesterol: 87 },
    { id: 355, name: "Subway 6\" Turkey Sub", brand: "Subway", category: "fast-food", emoji: "🥖", serving: "1 sub (233g)", calories: 280, protein: 18, carbs: 46, fat: 3.5, fiber: 5, sugar: 7, sodium: 760, cholesterol: 20 },
    { id: 356, name: "Subway 6\" Italian BMT", brand: "Subway", category: "fast-food", emoji: "🥖", serving: "1 sub (243g)", calories: 410, protein: 20, carbs: 44, fat: 18, fiber: 5, sugar: 7, sodium: 1290, cholesterol: 55 },
    { id: 357, name: "Pizza Slice (Pepperoni)", brand: "Generic", category: "fast-food", emoji: "🍕", serving: "1 slice (107g)", calories: 298, protein: 13, carbs: 34, fat: 12, fiber: 2.5, sugar: 3.6, sodium: 640, cholesterol: 28 },
    { id: 358, name: "Pizza Slice (Cheese)", brand: "Generic", category: "fast-food", emoji: "🍕", serving: "1 slice (107g)", calories: 266, protein: 12, carbs: 33, fat: 10, fiber: 2.3, sugar: 3.8, sodium: 590, cholesterol: 23 },
    { id: 359, name: "Burrito (Chicken)", brand: "Chipotle", category: "fast-food", emoji: "🌯", serving: "1 burrito (510g)", calories: 665, protein: 38, carbs: 74, fat: 22, fiber: 10, sugar: 4, sodium: 1410, cholesterol: 65 },
    { id: 360, name: "Taco (Beef, Hard Shell)", brand: "Taco Bell", category: "fast-food", emoji: "🌮", serving: "1 taco (78g)", calories: 170, protein: 8, carbs: 13, fat: 10, fiber: 3, sugar: 1, sodium: 310, cholesterol: 25 },
    { id: 361, name: "KFC Original Drumstick", brand: "KFC", category: "fast-food", emoji: "🍗", serving: "1 piece (59g)", calories: 130, protein: 13, carbs: 4, fat: 7, fiber: 0, sugar: 0, sodium: 350, cholesterol: 70 },
    { id: 362, name: "Hot Dog", brand: "Generic", category: "fast-food", emoji: "🌭", serving: "1 with bun (98g)", calories: 290, protein: 11, carbs: 24, fat: 17, fiber: 1, sugar: 4, sodium: 810, cholesterol: 35 },
    { id: 363, name: "Fish & Chips", brand: "Generic", category: "fast-food", emoji: "🐟", serving: "1 serving (300g)", calories: 585, protein: 22, carbs: 52, fat: 32, fiber: 3, sugar: 2, sodium: 720, cholesterol: 45 },
    { id: 364, name: "Caesar Salad (with dressing)", brand: "Generic", category: "fast-food", emoji: "🥗", serving: "1 bowl (250g)", calories: 360, protein: 15, carbs: 18, fat: 26, fiber: 3, sugar: 3, sodium: 780, cholesterol: 40 },
    { id: 365, name: "Fried Chicken Sandwich", brand: "Generic", category: "fast-food", emoji: "🍔", serving: "1 sandwich (220g)", calories: 490, protein: 24, carbs: 44, fat: 24, fiber: 2, sugar: 6, sodium: 990, cholesterol: 55 },
    { id: 366, name: "Onion Rings", brand: "Generic", category: "fast-food", emoji: "🧅", serving: "medium (117g)", calories: 411, protein: 5, carbs: 42, fat: 25, fiber: 2, sugar: 5, sodium: 587, cholesterol: 5 },
    { id: 367, name: "Mozzarella Sticks", brand: "Generic", category: "fast-food", emoji: "🧀", serving: "4 pieces (100g)", calories: 312, protein: 13, carbs: 27, fat: 17, fiber: 1, sugar: 2, sodium: 680, cholesterol: 30 },
    { id: 368, name: "Chicken Wrap", brand: "Generic", category: "fast-food", emoji: "🌯", serving: "1 wrap (260g)", calories: 420, protein: 26, carbs: 40, fat: 18, fiber: 3, sugar: 3, sodium: 880, cholesterol: 50 },
    { id: 369, name: "French Toast Sticks", brand: "Generic", category: "fast-food", emoji: "🍞", serving: "5 sticks (88g)", calories: 310, protein: 5, carbs: 37, fat: 16, fiber: 1, sugar: 12, sodium: 350, cholesterol: 30 },

    // ==================== INDIAN CUISINE ====================
    { id: 400, name: "Dal (Lentil Curry)", brand: "Homemade", category: "indian", emoji: "🍛", serving: "1 cup (200g)", calories: 198, protein: 12, carbs: 30, fat: 4, fiber: 8, sugar: 3, sodium: 480, cholesterol: 0 },
    { id: 401, name: "Chicken Tikka Masala", brand: "Generic", category: "indian", emoji: "🍛", serving: "1 cup (240g)", calories: 310, protein: 25, carbs: 15, fat: 17, fiber: 2, sugar: 6, sodium: 680, cholesterol: 85 },
    { id: 402, name: "Palak Paneer", brand: "Generic", category: "indian", emoji: "🍛", serving: "1 cup (220g)", calories: 260, protein: 14, carbs: 10, fat: 18, fiber: 4, sugar: 4, sodium: 520, cholesterol: 40 },
    { id: 403, name: "Butter Chicken", brand: "Generic", category: "indian", emoji: "🍛", serving: "1 cup (240g)", calories: 340, protein: 28, carbs: 12, fat: 20, fiber: 2, sugar: 5, sodium: 720, cholesterol: 90 },
    { id: 404, name: "Biryani (Chicken)", brand: "Homemade", category: "indian", emoji: "🍚", serving: "1 cup (250g)", calories: 320, protein: 18, carbs: 42, fat: 10, fiber: 2, sugar: 2, sodium: 540, cholesterol: 50 },
    { id: 405, name: "Roti / Chapati", brand: "Homemade", category: "indian", emoji: "🍞", serving: "1 roti (40g)", calories: 104, protein: 3.5, carbs: 18, fat: 2.5, fiber: 2, sugar: 0.3, sodium: 140, cholesterol: 0 },
    { id: 406, name: "Paratha (plain)", brand: "Homemade", category: "indian", emoji: "🍞", serving: "1 paratha (80g)", calories: 260, protein: 5, carbs: 36, fat: 10, fiber: 2, sugar: 1, sodium: 340, cholesterol: 0 },
    { id: 407, name: "Samosa (Potato)", brand: "Generic", category: "indian", emoji: "🥟", serving: "1 samosa (80g)", calories: 252, protein: 4, carbs: 28, fat: 14, fiber: 2, sugar: 2, sodium: 380, cholesterol: 0 },
    { id: 408, name: "Paneer Tikka", brand: "Generic", category: "indian", emoji: "🧀", serving: "6 pieces (150g)", calories: 270, protein: 18, carbs: 8, fat: 18, fiber: 1, sugar: 3, sodium: 420, cholesterol: 45 },
    { id: 409, name: "Aloo Gobi", brand: "Homemade", category: "indian", emoji: "🥔", serving: "1 cup (200g)", calories: 175, protein: 5, carbs: 22, fat: 8, fiber: 4, sugar: 4, sodium: 380, cholesterol: 0 },
    { id: 410, name: "Chole (Chickpea Curry)", brand: "Homemade", category: "indian", emoji: "🍛", serving: "1 cup (220g)", calories: 240, protein: 10, carbs: 34, fat: 8, fiber: 8, sugar: 4, sodium: 520, cholesterol: 0 },
    { id: 411, name: "Rajma (Kidney Bean Curry)", brand: "Homemade", category: "indian", emoji: "🍛", serving: "1 cup (220g)", calories: 210, protein: 11, carbs: 32, fat: 5, fiber: 10, sugar: 3, sodium: 480, cholesterol: 0 },
    { id: 412, name: "Dosa (plain)", brand: "Homemade", category: "indian", emoji: "🥞", serving: "1 dosa (85g)", calories: 133, protein: 3.5, carbs: 22, fat: 3.5, fiber: 1, sugar: 1, sodium: 200, cholesterol: 0 },
    { id: 413, name: "Masala Dosa", brand: "Homemade", category: "indian", emoji: "🥞", serving: "1 dosa (200g)", calories: 280, protein: 6, carbs: 40, fat: 11, fiber: 3, sugar: 2, sodium: 380, cholesterol: 0 },
    { id: 414, name: "Idli", brand: "Homemade", category: "indian", emoji: "🍙", serving: "2 idlis (80g)", calories: 118, protein: 3.2, carbs: 24, fat: 0.6, fiber: 1, sugar: 0.4, sodium: 280, cholesterol: 0 },
    { id: 415, name: "Upma", brand: "Homemade", category: "indian", emoji: "🥣", serving: "1 cup (200g)", calories: 220, protein: 5, carbs: 32, fat: 8, fiber: 3, sugar: 1, sodium: 420, cholesterol: 0 },
    { id: 416, name: "Poha", brand: "Homemade", category: "indian", emoji: "🍚", serving: "1 cup (180g)", calories: 244, protein: 4, carbs: 40, fat: 8, fiber: 2, sugar: 2, sodium: 350, cholesterol: 0 },
    { id: 417, name: "Raita (Yogurt)", brand: "Homemade", category: "indian", emoji: "🥛", serving: "1/2 cup (120g)", calories: 65, protein: 3, carbs: 6, fat: 3, fiber: 0.5, sugar: 5, sodium: 140, cholesterol: 10 },
    { id: 418, name: "Gulab Jamun", brand: "Generic", category: "indian", emoji: "🍬", serving: "2 pieces (80g)", calories: 290, protein: 4, carbs: 44, fat: 11, fiber: 0.5, sugar: 32, sodium: 80, cholesterol: 15 },
    { id: 419, name: "Jalebi", brand: "Generic", category: "indian", emoji: "🍬", serving: "3 pieces (75g)", calories: 270, protein: 2, carbs: 52, fat: 7, fiber: 0.3, sugar: 40, sodium: 30, cholesterol: 0 },
    { id: 420, name: "Kheer (Rice Pudding)", brand: "Homemade", category: "indian", emoji: "🍮", serving: "1/2 cup (120g)", calories: 175, protein: 4.5, carbs: 28, fat: 5.5, fiber: 0.3, sugar: 20, sodium: 55, cholesterol: 15 },
    { id: 421, name: "Paneer Butter Masala", brand: "Generic", category: "indian", emoji: "🍛", serving: "1 cup (240g)", calories: 350, protein: 16, carbs: 14, fat: 26, fiber: 2, sugar: 6, sodium: 640, cholesterol: 50 },
    { id: 422, name: "Tandoori Chicken", brand: "Generic", category: "indian", emoji: "🍗", serving: "1 piece (150g)", calories: 195, protein: 28, carbs: 4, fat: 7, fiber: 1, sugar: 2, sodium: 520, cholesterol: 80 },
    { id: 423, name: "Vada Pav", brand: "Street Food", category: "indian", emoji: "🍔", serving: "1 piece (140g)", calories: 290, protein: 6, carbs: 40, fat: 12, fiber: 3, sugar: 3, sodium: 440, cholesterol: 0 },
    { id: 424, name: "Pav Bhaji", brand: "Street Food", category: "indian", emoji: "🍞", serving: "1 plate (300g)", calories: 400, protein: 10, carbs: 52, fat: 18, fiber: 6, sugar: 8, sodium: 680, cholesterol: 15 },
    { id: 425, name: "Lassi (Sweet)", brand: "Generic", category: "indian", emoji: "🥛", serving: "1 glass (250ml)", calories: 180, protein: 6, carbs: 28, fat: 5, fiber: 0, sugar: 24, sodium: 95, cholesterol: 18 },

    // ==================== CONDIMENTS & EXTRAS ====================
    { id: 450, name: "Olive Oil", brand: "Generic", category: "snacks", emoji: "🫒", serving: "1 tbsp (14ml)", calories: 119, protein: 0, carbs: 0, fat: 14, fiber: 0, sugar: 0, sodium: 0, cholesterol: 0 },
    { id: 451, name: "Honey", brand: "Generic", category: "snacks", emoji: "🍯", serving: "1 tbsp (21g)", calories: 64, protein: 0.1, carbs: 17, fat: 0, fiber: 0, sugar: 17, sodium: 1, cholesterol: 0 },
    { id: 452, name: "Ketchup", brand: "Heinz", category: "snacks", emoji: "🍅", serving: "1 tbsp (17g)", calories: 20, protein: 0.2, carbs: 5.3, fat: 0, fiber: 0, sugar: 3.7, sodium: 160, cholesterol: 0 },
    { id: 453, name: "Mayonnaise", brand: "Generic", category: "snacks", emoji: "🥚", serving: "1 tbsp (15g)", calories: 94, protein: 0.1, carbs: 0.1, fat: 10, fiber: 0, sugar: 0.1, sodium: 88, cholesterol: 6 },
    { id: 454, name: "Soy Sauce", brand: "Generic", category: "snacks", emoji: "🫙", serving: "1 tbsp (18ml)", calories: 9, protein: 0.9, carbs: 1, fat: 0, fiber: 0, sugar: 0.4, sodium: 879, cholesterol: 0 },
    { id: 455, name: "Salsa", brand: "Generic", category: "snacks", emoji: "🫙", serving: "2 tbsp (32g)", calories: 10, protein: 0.3, carbs: 2, fat: 0, fiber: 0.5, sugar: 1.3, sodium: 200, cholesterol: 0 },
    { id: 456, name: "Ranch Dressing", brand: "Generic", category: "snacks", emoji: "🫙", serving: "2 tbsp (30g)", calories: 129, protein: 0.4, carbs: 1.8, fat: 13, fiber: 0, sugar: 1, sodium: 270, cholesterol: 5 },
    { id: 457, name: "Balsamic Vinaigrette", brand: "Generic", category: "snacks", emoji: "🫙", serving: "2 tbsp (30ml)", calories: 90, protein: 0, carbs: 5, fat: 8, fiber: 0, sugar: 4, sodium: 260, cholesterol: 0 },
    { id: 458, name: "Maple Syrup", brand: "Generic", category: "snacks", emoji: "🍯", serving: "2 tbsp (40ml)", calories: 104, protein: 0, carbs: 27, fat: 0, fiber: 0, sugar: 24, sodium: 4, cholesterol: 0 },
    { id: 459, name: "Cream of Mushroom Soup", brand: "Campbell's", category: "snacks", emoji: "🍄", serving: "1 cup (248g)", calories: 130, protein: 2, carbs: 9, fat: 9, fiber: 0, sugar: 1, sodium: 870, cholesterol: 5 },
    { id: 460, name: "Chia Seeds", brand: "Generic", category: "snacks", emoji: "🌾", serving: "2 tbsp (28g)", calories: 138, protein: 4.7, carbs: 12, fat: 8.7, fiber: 9.8, sugar: 0, sodium: 5, cholesterol: 0 },
    { id: 461, name: "Flax Seeds", brand: "Generic", category: "snacks", emoji: "🌾", serving: "2 tbsp (20g)", calories: 110, protein: 3.8, carbs: 6, fat: 8.5, fiber: 5.6, sugar: 0.3, sodium: 6, cholesterol: 0 },
    { id: 462, name: "Sunflower Seeds", brand: "Generic", category: "snacks", emoji: "🌻", serving: "1/4 cup (35g)", calories: 204, protein: 7.3, carbs: 7, fat: 18, fiber: 3, sugar: 0.9, sodium: 1, cholesterol: 0 },
    { id: 463, name: "Dried Mango", brand: "Generic", category: "snacks", emoji: "🥭", serving: "1/4 cup (40g)", calories: 128, protein: 0.8, carbs: 31, fat: 0.5, fiber: 1, sugar: 27, sodium: 50, cholesterol: 0 },

    // ==================== PREPARED MEALS & MISC ====================
    { id: 500, name: "Scrambled Eggs (2 eggs)", brand: "Homemade", category: "protein", emoji: "🍳", serving: "2 eggs (122g)", calories: 182, protein: 12, carbs: 2, fat: 14, fiber: 0, sugar: 1.4, sodium: 342, cholesterol: 370 },
    { id: 501, name: "Pancakes (3 stack)", brand: "Homemade", category: "grains", emoji: "🥞", serving: "3 pancakes (180g)", calories: 417, protein: 10, carbs: 58, fat: 16, fiber: 2, sugar: 12, sodium: 600, cholesterol: 80 },
    { id: 502, name: "Waffle", brand: "Generic", category: "grains", emoji: "🧇", serving: "1 waffle (75g)", calories: 218, protein: 5.5, carbs: 25, fat: 11, fiber: 0.8, sugar: 4, sodium: 383, cholesterol: 52 },
    { id: 503, name: "Spaghetti with Marinara", brand: "Homemade", category: "grains", emoji: "🍝", serving: "1 plate (350g)", calories: 420, protein: 14, carbs: 72, fat: 8, fiber: 6, sugar: 10, sodium: 640, cholesterol: 0 },
    { id: 504, name: "Spaghetti Bolognese", brand: "Homemade", category: "grains", emoji: "🍝", serving: "1 plate (400g)", calories: 520, protein: 28, carbs: 60, fat: 18, fiber: 5, sugar: 8, sodium: 720, cholesterol: 55 },
    { id: 505, name: "Fried Rice", brand: "Homemade", category: "grains", emoji: "🍚", serving: "1 cup (200g)", calories: 238, protein: 7, carbs: 36, fat: 8, fiber: 1.5, sugar: 1, sodium: 680, cholesterol: 45 },
    { id: 506, name: "Stir Fry (Chicken & Veg)", brand: "Homemade", category: "protein", emoji: "🥘", serving: "1 cup (250g)", calories: 280, protein: 24, carbs: 18, fat: 12, fiber: 4, sugar: 6, sodium: 720, cholesterol: 60 },
    { id: 507, name: "Grilled Cheese Sandwich", brand: "Homemade", category: "grains", emoji: "🧀", serving: "1 sandwich (160g)", calories: 440, protein: 16, carbs: 28, fat: 30, fiber: 2, sugar: 4, sodium: 860, cholesterol: 65 },
    { id: 508, name: "PB&J Sandwich", brand: "Homemade", category: "grains", emoji: "🥜", serving: "1 sandwich (130g)", calories: 390, protein: 12, carbs: 52, fat: 16, fiber: 4, sugar: 20, sodium: 410, cholesterol: 0 },
    { id: 509, name: "Tuna Salad", brand: "Homemade", category: "protein", emoji: "🥗", serving: "1 cup (200g)", calories: 280, protein: 26, carbs: 10, fat: 16, fiber: 1, sugar: 4, sodium: 520, cholesterol: 45 },
    { id: 510, name: "Chicken Salad", brand: "Homemade", category: "protein", emoji: "🥗", serving: "1 cup (200g)", calories: 320, protein: 28, carbs: 6, fat: 20, fiber: 1, sugar: 2, sodium: 480, cholesterol: 70 },
    { id: 511, name: "Sushi Roll (California)", brand: "Generic", category: "protein", emoji: "🍣", serving: "8 pieces (185g)", calories: 255, protein: 9, carbs: 38, fat: 7, fiber: 2, sugar: 9, sodium: 540, cholesterol: 15 },
    { id: 512, name: "Sushi Roll (Salmon)", brand: "Generic", category: "protein", emoji: "🍣", serving: "8 pieces (185g)", calories: 280, protein: 14, carbs: 36, fat: 9, fiber: 2, sugar: 8, sodium: 520, cholesterol: 20 },
    { id: 513, name: "Ramen (with pork broth)", brand: "Generic", category: "grains", emoji: "🍜", serving: "1 bowl (500ml)", calories: 450, protein: 18, carbs: 56, fat: 16, fiber: 2, sugar: 4, sodium: 1820, cholesterol: 45 },
    { id: 514, name: "Pho (Beef)", brand: "Generic", category: "protein", emoji: "🍜", serving: "1 bowl (600ml)", calories: 380, protein: 24, carbs: 42, fat: 12, fiber: 1, sugar: 4, sodium: 1400, cholesterol: 50 },
    { id: 515, name: "Mac and Cheese", brand: "Kraft", category: "grains", emoji: "🧀", serving: "1 cup (200g)", calories: 350, protein: 12, carbs: 47, fat: 13, fiber: 2, sugar: 6, sodium: 710, cholesterol: 15 },
    { id: 516, name: "Chili (beef & beans)", brand: "Homemade", category: "protein", emoji: "🌶️", serving: "1 cup (253g)", calories: 290, protein: 22, carbs: 24, fat: 12, fiber: 6, sugar: 4, sodium: 840, cholesterol: 40 },
    { id: 517, name: "Overnight Oats", brand: "Homemade", category: "grains", emoji: "🥣", serving: "1 jar (300g)", calories: 350, protein: 12, carbs: 50, fat: 12, fiber: 8, sugar: 18, sodium: 120, cholesterol: 5 },
    { id: 518, name: "Acai Bowl", brand: "Generic", category: "fruits", emoji: "🫐", serving: "1 bowl (300g)", calories: 380, protein: 6, carbs: 60, fat: 14, fiber: 8, sugar: 35, sodium: 20, cholesterol: 0 },
    { id: 519, name: "Avocado Toast", brand: "Homemade", category: "grains", emoji: "🥑", serving: "1 slice (150g)", calories: 230, protein: 6, carbs: 22, fat: 14, fiber: 6, sugar: 2, sodium: 280, cholesterol: 0 },
    { id: 520, name: "Omelette (3 egg, veggie)", brand: "Homemade", category: "protein", emoji: "🍳", serving: "1 omelette (200g)", calories: 280, protein: 20, carbs: 6, fat: 20, fiber: 2, sugar: 3, sodium: 440, cholesterol: 560 },
];

// Category labels for display
export const FOOD_CATEGORIES = {
    all: { label: "All Foods", emoji: "🍽️" },
    protein: { label: "Protein & Meats", emoji: "🥩" },
    grains: { label: "Grains & Carbs", emoji: "🌾" },
    fruits: { label: "Fruits", emoji: "🍎" },
    vegetables: { label: "Vegetables", emoji: "🥦" },
    dairy: { label: "Dairy", emoji: "🧀" },
    beverages: { label: "Beverages", emoji: "🥤" },
    "indian-drinks": { label: "Indian Drinks", emoji: "🧋" },
    "indian-snacks": { label: "Indian Snacks & Biscuits", emoji: "🍪" },
    snacks: { label: "Snacks & Extras", emoji: "🍪" },
    "fast-food": { label: "Fast Food", emoji: "🍔" },
    indian: { label: "Indian Cuisine", emoji: "🍛" },
};
